"""
``sajha completion bash|zsh|fish`` — completion scripts generated from the argparse tree,
so they never drift from the commands.  Tool and prompt names complete live
(``sajha tools list --names``) for ``tools show|call``.

    eval "$(sajha completion bash)"          # ~/.bashrc
    eval "$(sajha completion zsh)"           # ~/.zshrc
    sajha completion fish > ~/.config/fish/completions/sajha.fish
"""

from __future__ import annotations

import argparse
from typing import Dict, List, Tuple


def _subparsers(parser: argparse.ArgumentParser) -> Dict[str, argparse.ArgumentParser]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def _options(parser: argparse.ArgumentParser) -> List[str]:
    opts = []
    for action in parser._actions:
        opts.extend(o for o in action.option_strings if o.startswith("--"))
    return sorted(set(opts))


def tree(parser: argparse.ArgumentParser) -> Tuple[List[str], Dict[str, List[str]], Dict[str, List[str]]]:
    """(top-level commands, command -> actions, 'cmd' or 'cmd action' -> options)."""
    top = _subparsers(parser)
    actions: Dict[str, List[str]] = {}
    options: Dict[str, List[str]] = {"": _options(parser)}
    for name, p in top.items():
        subs = _subparsers(p)
        actions[name] = sorted(subs)
        options[name] = _options(p)
        for sname, sp in subs.items():
            options[f"{name} {sname}"] = _options(sp)
    return sorted(top), actions, options


def script(shell: str, parser: argparse.ArgumentParser) -> str:
    top, actions, options = tree(parser)
    if shell == "bash":
        return _bash(top, actions, options)
    if shell == "zsh":
        return "autoload -U +X bashcompinit && bashcompinit\n" + _bash(top, actions, options)
    return _fish(top, actions, options)


def _bash(top, actions, options) -> str:
    cases_actions = "\n".join(f'        {c}) acts="{" ".join(a)}" ;;' for c, a in actions.items() if a)
    cases_opts = "\n".join(f'        "{k}") opts="{" ".join(v)}" ;;' for k, v in options.items())
    return f"""# sajha bash completion (generated by 'sajha completion bash')
_sajha() {{
    local cur cmd act acts opts i
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    cmd=""; act=""
    for ((i=1; i<COMP_CWORD; i++)); do
        case "${{COMP_WORDS[i]}}" in -*) continue ;; esac
        if [[ -z "$cmd" ]]; then cmd="${{COMP_WORDS[i]}}"; elif [[ -z "$act" ]]; then act="${{COMP_WORDS[i]}}"; break; fi
    done
    acts=""
    case "$cmd" in
{cases_actions}
    esac
    opts=""
    case "$cmd${{act:+ $act}}" in
{cases_opts}
    esac
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") ); return
    fi
    if [[ -z "$cmd" ]]; then
        COMPREPLY=( $(compgen -W "{' '.join(top)}" -- "$cur") ); return
    fi
    if [[ -z "$act" && -n "$acts" ]]; then
        COMPREPLY=( $(compgen -W "$acts" -- "$cur") ); return
    fi
    case "$cmd $act" in
        "tools show"|"tools call")
            COMPREPLY=( $(compgen -W "$(sajha tools list --names 2>/dev/null)" -- "$cur") ) ;;
        "prompts get")
            COMPREPLY=( $(compgen -W "$(sajha prompts list --json 2>/dev/null | sed -n 's/^    \\"name\\": \\"\\(.*\\)\\",*$/\\1/p')" -- "$cur") ) ;;
        "completion "*) COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ) ;;
        *) COMPREPLY=( $(compgen -f -- "$cur") ) ;;
    esac
}}
complete -F _sajha sajha
"""


def _fish(top, actions, options) -> str:
    lines = ["# sajha fish completion (generated by 'sajha completion fish')",
             "complete -c sajha -f"]
    lines.append(f"complete -c sajha -n '__fish_use_subcommand' -a '{' '.join(top)}'")
    for cmd, acts in actions.items():
        if acts:
            lines.append(f"complete -c sajha -n '__fish_seen_subcommand_from {cmd}; and not "
                         f"__fish_seen_subcommand_from {' '.join(acts)}' -a '{' '.join(acts)}'")
    for opt in options.get("", []):
        lines.append(f"complete -c sajha -l {opt[2:]}")
    lines.append("complete -c sajha -n '__fish_seen_subcommand_from show call' "
                 "-a '(sajha tools list --names 2>/dev/null)'")
    return "\n".join(lines) + "\n"
