{{- if and .Values.podDisruptionBudget.enabled (include "sajha.multiPod" .) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sajha.fullname" . }}
  labels:
    {{- include "sajha.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "sajha.selectorLabels" . | nindent 6 }}
{{- end }}
