#!/usr/bin/env python3
"""Render the Kustomize manifests in deployment/k8s from the Helm chart (charts/sajha).

    python deployment/k8s/render.py            # rewrite base/ and overlays/*/
    python deployment/k8s/render.py --check    # exit 1 when the files are out of date

The chart is the source: base/ holds the objects that are identical in every overlay,
and each overlay holds the rest of its own render (values-<overlay>.yaml). Chart-managed
Secrets and the helm test Pod are left out; create the Secrets as deployment/k8s/README.md
says. Needs the helm binary (HELM env var or on PATH).

Copyright All rights Reserved 2025-2030, Ashutosh Sinha
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
CHART = HERE.parent.parent / 'charts' / 'sajha'
OVERLAYS = ('dev', 'prod')
HEADER = ('# Generated by deployment/k8s/render.py from charts/sajha and {src}.\n'
          '# Do not edit: change the chart or the values file and re-run the script.\n')
DROP_LABELS = ('helm.sh/chart', 'app.kubernetes.io/managed-by')


def helm_render(values: Path) -> list[dict]:
    helm = os.environ.get('HELM') or shutil.which('helm')
    if not helm:
        sys.exit('render.py: helm not found (set HELM or put it on PATH)')
    out = subprocess.run([helm, 'template', 'sajha', str(CHART), '-f', str(values)],
                         check=True, capture_output=True, text=True).stdout
    docs = []
    for doc in yaml.safe_load_all(out):
        if not doc or doc.get('kind') == 'Secret':
            continue
        if 'helm.sh/hook' in (doc['metadata'].get('annotations') or {}):
            continue
        clean(doc)
        docs.append(doc)
    return docs


def clean(node):
    """Drop Helm's bookkeeping labels (selectors never carry them)."""
    if isinstance(node, dict):
        if isinstance(node.get('labels'), dict):
            for drop in DROP_LABELS:
                node['labels'].pop(drop, None)
        for v in node.values():
            clean(v)
    elif isinstance(node, list):
        for v in node:
            clean(v)


def key(doc: dict) -> tuple:
    return doc['kind'], doc['metadata']['name']


def dump(docs: list[dict], src: str) -> str:
    body = '---\n'.join(yaml.safe_dump(d, sort_keys=False, width=100) for d in docs)
    return HEADER.format(src=src) + body


def plan() -> dict[Path, str]:
    renders = {o: helm_render(HERE / f'values-{o}.yaml') for o in OVERLAYS}
    first = {key(d): d for d in renders[OVERLAYS[0]]}
    common = [d for k, d in first.items()
              if all(any(key(x) == k and x == d for x in renders[o]) for o in OVERLAYS[1:])]
    common_keys = {key(d) for d in common}
    files = {HERE / 'base' / 'sajha-common.yaml': dump(common, 'every values-*.yaml')}
    for o in OVERLAYS:
        rest = [d for d in renders[o] if key(d) not in common_keys]
        files[HERE / 'overlays' / o / f'sajha-{o}.yaml'] = dump(rest, f'values-{o}.yaml')
    return files


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--check', action='store_true', help='compare instead of writing')
    a = ap.parse_args(argv)
    stale = []
    for path, text in plan().items():
        if a.check:
            if not path.exists() or path.read_text(encoding='utf-8') != text:
                stale.append(path)
        else:
            path.write_text(text, encoding='utf-8')
            print(f'wrote {path.relative_to(HERE)}')
    for path in stale:
        print(f'out of date: {path.relative_to(HERE)} (run deployment/k8s/render.py)')
    return 1 if stale else 0


if __name__ == '__main__':
    sys.exit(main())
